# Generated by Django 5.0.2 on 2024-03-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_profile_completed'),
        ('transactions', '0008_alter_transaction_account_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('account', 'name')},
        ),
    ]
