# Generated by Django 5.0.2 on 2024-03-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_profile_completed'),
        ('budgets', '0004_alter_budget_start_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('account', 'name')},
        ),
    ]
