# Generated by Django 5.0.2 on 2024-03-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_alter_budget_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='is_repetitive',
            field=models.BooleanField(default=False),
        ),
    ]
